name: engg_chemistry_study_assist
description: "An app that will be helpful in studying engineering chemistry"

publish_to: "none"

version: 1.6.0+8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  syncfusion_flutter_pdfviewer: ^29.2.7
  google_fonts: ^6.1.0
  firebase_database: ^11.3.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.4
  mailto: ^2.0.0
  cloud_firestore: ^5.6.8
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/unit2/
    - assets/unit3/
    - assets/unit4/
    - assets/unit5/
    - assets/unit6/
