class QuizQuestion {
  int id;
  String question;
  List options;
  int correctAns;

  QuizQuestion(
      {required this.id,
      required this.question,
      required this.options,
      required this.correctAns});
}

List questionList = [
  QuizQuestion(
      id: 1,
      question:
          "For the phenomenon of Reverse Osmosis, pressure applied should be ____ osmotic pressure",
      options: ["Equal to ", "Less than ", "Greater than ", "None of these"],
      correctAns: 3),
  QuizQuestion(
      id: 2,
      question:
          "Water obtained in the process of demineralization has hardness about  ",
      options: ["0-2 ppm", "20-50 ppm", "100-200 ppm", "50-100 ppm"],
      correctAns: 1),
  QuizQuestion(
      id: 3,
      question: "Zeolite process cannot remove_______",
      options: ["Ca2+", "Mg2+", "Mn2+", "Na+"],
      correctAns: 4),
  QuizQuestion(
      id: 4,
      question: "Exhausted zeolite bed can be regenerated by using _____",
      options: ["10% NaCl", "10% CaCl2", "20% MgCl2", "20% FeCl2"],
      correctAns: 1),
  QuizQuestion(
      id: 5,
      question:
          "Polymers used in making semi permeable membrane in reverse osmosis process",
      options: [
        "cellulose acetate",
        "polymethyl acrylate",
        "both a and b",
        "none of the above"
      ],
      correctAns: 3),
  QuizQuestion(
      id: 6,
      question: "Rain water is ____ water",
      options: ["hard", "soft", "impure", "double distilled"],
      correctAns: 2),
  QuizQuestion(
      id: 7,
      question: "+CO2 The hardness removed by above method is ___ hardness.",
      options: ["Mild", "Carbonate", "Non-Carbonate", "Permanent "],
      correctAns: 2),
  QuizQuestion(
      id: 8,
      question:
          "The impurities in water having paricle size greater than ___ are suspended particles.",
      options: ["1000 A", "10 A", "0.1 A", "1 A"],
      correctAns: 2),
  QuizQuestion(
      id: 9,
      question: "What type of hardness can be removed by boiling merely",
      options: [
        "Temporary Hardness",
        "Permanent Hardness",
        "Both of the above",
        "None of the above"
      ],
      correctAns: 1),
  QuizQuestion(
      id: 10,
      question:
          "In ______ method, concentration of brine decreases by applying  direct  electric  current.",
      options: ["Ion exchange", "Zeolite", "Electrodialysis", "Osmosis "],
      correctAns: 3),
  QuizQuestion(
      id: 11,
      question: "Suspended impurities can be separated by______.",
      options: ["Zeolite process", "Ion Exchange", "Filtration", "Osmosis"],
      correctAns: 3),
  QuizQuestion(
      id: 12,
      question:
          "Water which does not form lather readily with soap is called as 	",
      options: ["	Soft water", "Pure water", "Impure Water", "Hard Water"],
      correctAns: 4),
  QuizQuestion(
      id: 13,
      question: "The colour of metal-EBT complex is______.",
      options: ["Colourless", "Wine red", "Blue", "Yellow "],
      correctAns: 2),
  QuizQuestion(
      id: 14,
      question:
          "In alkalinity titration, second end point is called as 	end point.",
      options: ["Phenolpthalein", "EBT", "Methyl orange", "Fluoroscien "],
      correctAns: 3),
  QuizQuestion(
      id: 15,
      question: "Hardness determination is _________ type of titration.",
      options: ["Precipitation", "Redox", "Complexometric", "Acid-base "],
      correctAns: 3),
  QuizQuestion(
      id: 16,
      question: "Temporary hardness of water is due to_____",
      options: ["Chlorides", "Bicarbonates", "Nitrates", "Heavy metal salts "],
      correctAns: 2),
  QuizQuestion(
      id: 17,
      question: "In EDTA method, pH of the buffer solution is ___.",
      options: ["5", "8", "10", "7"],
      correctAns: 3),
  QuizQuestion(
      id: 18,
      question: "M-EDTA complex is 	.",
      options: [
        "Neutral",
        "Negatively charged",
        "Positively charged",
        "None of these "
      ],
      correctAns: 2),
  QuizQuestion(
      id: 19,
      question:
          "Dissolved CO2 from water is removed by adding suitable amount of ____ .",
      options: ["NH3", "CO2", "C.	H2S", "H2O"],
      correctAns: 1),
  QuizQuestion(
      id: 20,
      question:
          "Galvanic corrosion can be avoided by suspending ______ plates.",
      options: ["Steel", "Chromium", "Silver", "Zinc"],
      correctAns: 4),
  QuizQuestion(
      id: 21,
      question: "Presence of silica in boiler water causes",
      options: ["Sludge formation", "Priming", "Foaming", "Scale formation"],
      correctAns: 4),
  QuizQuestion(
      id: 22,
      question:
          "Normally sludge formation is towards the ___	parts of the boiler",
      options: ["Hotter", "Bottom", "Cooler", "Middle"],
      correctAns: 3),
  QuizQuestion(
      id: 23,
      question:
          "Caustic embrittlement can be avoided by treating boiler feed water with",
      options: [
        "Sodium Carbonate",
        "Sodium phosphate",
        "Sodium chloride",
        "Sodium sulphate",
      ],
      correctAns: 2),
  QuizQuestion(
      id: 24,
      question:
          "By using ___	chelating compound scales and sludges can be converted into soluble complexes.",
      options: ["Na2CO3", "EDTA", "Na2PO4", "CaCO3"],
      correctAns: 2),
  QuizQuestion(
      id: 25,
      question: ". The other name of zeolite process is ____ process",
      options: [
        "Ion exchange",
        "Permutit",
        "Demineralization",
        "Coagulation  "
      ],
      correctAns: 2),
  QuizQuestion(
      id: 26,
      question:
          "In EDTA-hard water titration along with indicator with ______ is added. ",
      options: ["Alkalinity", "Acidity", "pH", "Neutrality"],
      correctAns: 3),
  QuizQuestion(
      id: 27,
      question: "If P = M ,then ______ alkalinities are present.",
      options: ["OH-", "HCO3-", "CO3--", "OH- and CO3--"],
      correctAns: 1),
  QuizQuestion(
      id: 28,
      question: "If P < 0.5M ,then ______ alkalinities are present.",
      options: ["OH-", "HCO3-", "CO3--", "HCO3- and CO3--"],
      correctAns: 4),
  QuizQuestion(
      id: 29,
      question: "If P > 0.5M ,then ______ alkalinities are present.",
      options: ["OH-", "HCO3-", "CO3--", "OH- and CO3--"],
      correctAns: 4),
  QuizQuestion(
      id: 30,
      question: "In EDTA method, pH of the buffer solution is _____ .",
      options: ["5", "8", "10", "7"],
      correctAns: 3),
];
